services:
  ilchul-backend-green:
    image: ${BACKEND_IMAGE}
    container_name: ilchul-backend-green
    ports:
      - "8082:8080"
    env_file:
      - .env
    environment:
      - OTEL_SERVICE_NAME=ilchul-backend
      - OTEL_RESOURCE_ATTRIBUTES=service.version=1.0.1,deployment.color=green
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://tempo:4318
      - OTEL_METRICS_EXPORTER=none
      - OTEL_LOGS_EXPORTER=none
    restart: unless-stopped
    networks:
      - ilchul-network
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:8080/actuator/health || exit 1"]
      interval: 20s
      timeout: 10s
      retries: 5
      start_period: 120s

  ilchul-frontend-green:
    image: ${FRONTEND_IMAGE}
    container_name: ilchul-frontend-green
    ports:
      - "3002:3000"
    env_file:
      - .env
    depends_on:
      - ilchul-backend-green
    restart: unless-stopped
    networks:
      - ilchul-network
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://127.0.0.1:3000 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 40s

networks:
  ilchul-network:
    external: true
    name: ilchul-network