services:
  ilchul-backend-blue:
    image: ${BACKEND_IMAGE}
    container_name: ilchul-backend-blue
    ports:
      - "8081:8080"
    env_file:
      - .env
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - ilchul-network
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:8080/actuator/health || exit 1"]
      interval: 20s
      timeout: 10s
      retries: 5
      start_period: 120s

  ilchul-frontend-blue:
    image: ${FRONTEND_IMAGE}
    container_name: ilchul-frontend-blue
    ports:
      - "3001:3000"
    env_file:
      - .env
    depends_on:
      - backend_blue
    restart: unless-stopped
    networks:
      - ilchul-network
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://127.0.0.1:3000 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 40s

networks:
  ilchul-network:
    external: true
    name: ilchul-network